version: "3"

services:
    workspace:
        container_name: guilde-app
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        volumes:
            - ./:/var/www/html:cached
            - ./.docker/nginx/sites-enabled:/etc/nginx/sites-enabled
        tty: true
        ports:
            - "9003:9000"
            - "80:80"
        depends_on:
            - mysql
        networks:
            - guild-network
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        command: --explicit_defaults_for_timestamp
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_PASSWORD: laravel
        networks:
            - guild-network
    redis:
        container_name: guild-redis
        build: ./.docker/redis
        volumes:
            - ./.docker/redis/data:/data
        ports:
            - "63799:6379"
        networks:
            - guild-network
networks:
    guild-network:
        driver: bridge
