<?php

namespace App\Models;

use App\Services\FileService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['tags'];

    public static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        self::deleted(function ($cate) {
            app(FileService::class)->delete($cate->image);
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function getImageShowAttribute()
    {
        return $this->image ? asset('storage/'.$this->image) : '/images/no-image.png';
    }
}
