<?php

namespace App\Models;

use App\Services\FileService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        self::deleted(function ($cate) {
            app(FileService::class)->delete($cate->image);
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}
