name: Laravel
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Add phpcs
      run: |
        composer global require "squizlabs/php_codesniffer=*"
        composer global config bin-dir --absolute

    - name: Add standard
      run: |
        git clone https://github.com/wataridori/framgia-php-codesniffer.git ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Framgia
    - name: config installed path
      run: |
        cd ~/.config/composer/vendor/bin
        ls
        ~/.config/composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Framgia

    - name: Check phpcs
      run: |
        sudo ~/.config/composer/vendor/bin/phpcs --standard=Framgia app --ignore=*/app/Lib/*

    - name: Generate key
      run: php artisan key:generate

    - name: Migrate DB
      run: php artisan migrate --seed

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
